language: objective-c

osx_image: xcode7.3


script:
  - set -o pipefail && xcodebuild build -workspace Example/FerrisMenu.xcworkspace -scheme FerrisMenu-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES | xcpretty

