use_frameworks!

target 'FerrisMenu_Example' do
  #pod 'FerrisMenu', :path => '../'
  pod 'FerrisMenu', :path => '/Users/gene/Development/xcode/gene/Swift/FerrisMenu/'
end

target 'FerrisMenu_Tests' do
  pod 'FerrisMenu', :path => '/Users/gene/Development/xcode/gene/Swift/FerrisMenu/'
  #pod 'FerrisMenu', :path => '../'
end


