language: objective-c
osx_image: xcode7.3

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N


script:
- xctool -workspace Example/FerrisMenu.xcworkspace -scheme FerrisMenu-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES build | xcpretty -c




# http://docs.travis-ci.com/user/languages/objective-c/